polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='firstview'),
    path('<int:tournament_id>', views.firstview, name="firstview"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    # path('tournament', views.tournament, name='tournament'),
    # path('existing', views.existing, name="tourexisting"),
    path('choose', views.choose, name="choose"),
    path('choosetournament', views.choosetournament, name="choosetournament"),
    path('<int:tournament_id>/<int:level_id>/teams/', views.teams, name='teams'),
    path('<int:tournament_id>/<int:level_id>/', views.categories, name='category'),
    path('<int:tournament_id>/<int:level_id>/<int:category_id>/', views.questions, name='question'),
    path('<int:tournament_id>/<int:level_id>/<int:category_id>/<int:question_id>', views.specquestion, name='specquestion'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:question_id>/', views.questionstatus, name="questionstatus")
]

quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('master/', include('master.urls'))
]

polls/models.py
from django.db import models
from django.utils import timezone

class Tournament(models.Model):
    tournament_name = models.CharField(max_length=200, default=None, null=True, blank=True)
    user_id = models.CharField(max_length=200, default=None, null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.tournament_name

class Level(models.Model):
    level_name =  models.CharField(max_length=200)
    tournament_id = models.ForeignKey(Tournament, default=None, null=True, blank=True, on_delete=models.CASCADE)
    image_url = models.CharField(max_length=2083, blank=True)
    negative_marking = models.IntegerField()
    def __str__(self):
        return self.level_name
    

TEAMIMAGES = (
    ("https://cms-assets.tutsplus.com/uploads/users/346/posts/31688/image/sportslogos16.jpg","Bulls"),
    ("https://cmkt-image-prd.global.ssl.fastly.net/0.1.0/ps/5942957/300/200/m1/fpnw/wm0/mockuppanda-.jpg?1551077845&s=2efd525056f579874e9030216c4d7c9c","Panda"),
    ("https://designrshub-designrshub.netdna-ssl.com/wp-content/uploads/2019/01/sports-animal-mascot-logo-design-ideas-08.jpg","Shark"),
    ("https://designrshub-designrshub.netdna-ssl.com/wp-content/uploads/2019/01/sports-animal-mascot-logo-design-ideas-13.jpg","Deer"),
    ("https://cdn2.vectorstock.com/i/1000x1000/34/31/wild-wolf-esport-mascot-logo-design-vector-27463431.jpg","Wolf"),
    ("https://designrshub-designrshub.netdna-ssl.com/wp-content/uploads/2019/01/sports-animal-mascot-logo-design-ideas-18.jpg","Fox")
)
class Team(models.Model):
    tournament_id = models.ForeignKey(Tournament, default=None, null=True, blank=True, on_delete=models.CASCADE)
    team_name = models.CharField(max_length=2083)
    team_points = models.IntegerField(default=0)
    images = models.CharField(
        max_length=2000,
        choices=TEAMIMAGES,
        default=None,
        blank = True,
        null = True,
    )

class Category(models.Model):
    tournament_id = models.ForeignKey(Tournament, default=None, null=True, blank=True, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=2083)
    image_url = models.CharField(max_length=2083, blank=True, default="http://via.placeholder.com/72")
    def __str__(self):
        return self.category_name

CHOICES = (
    ("NA","Not Answered"),
    ("PQ","Passed Question"),
    ("RA","Right Answer"),
    ("WA","Wrong Answer")
)
class Question(models.Model):
    tournament_id = models.ForeignKey(Tournament, default=None, null=True, blank=True, on_delete=models.CASCADE)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=5000)
    question_number = models.IntegerField()
    image_url = models.CharField(max_length=2083, blank=True)
    marks_alloted = models.IntegerField()
    time_alloted = models.IntegerField(default=60)
    team_choose = models.ForeignKey(Team, on_delete=models.CASCADE, default=None, null=True, blank=True)
    pass_count = models.IntegerField()
    status = models.CharField(
        max_length=2,
        choices=CHOICES,
    default="NA",
    )
    answer = models.CharField(max_length=5000)
    def __str__(self):
        return self.question_text
    class Meta:
        ordering = ['marks_alloted']

polls/forms.py
from django import forms

from .models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('status',)

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Level
from .models import Category, Question, Team, Tournament
from django.http import HttpResponseRedirect
# from django.views.generic import TemplateView
from django.shortcuts import reverse
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse


def index(request):
    if request.session.get("user"):
        pagetogo = "/choose"
    else:
        pagetogo = "/login"
    user=User.objects.all()
    return render(request, 'index.html', {"pagetogo":pagetogo,'user':user})


def firstview(request, tournament_id):
    if not request.user.is_authenticated:
        return render(request, "login.html", {"message": None})
    else:
        
        if not request.session.get("tournament"):
            url = "/master"+"/login/jeopardy"
            user = request.user
            request.session["user"]= request.user.id
            return redirect(url, {"user":user})
        else:
            t = request.session.get("tournament")
            tournament = Tournament.objects.get(pk=t)
            user = request.user
            levels = Level.objects.all()
            request.session["user"]= request.user.id
        return render(request, 'firstview.html', {"user":user.first_name, 'levels':levels,'tournament':tournament, 't':t})

def choose(request):
    user = request.user
    request.session["user"]= request.user.id
    return render(request, 'choose.html', {'user':user})

def choosetournament(request):
    user=request.session.get("user")
    user=User.objects.get(pk=user)
    tournaments = Tournament.objects.all().filter(user_id=user)
    if request.method == "POST":
        if not request.POST.get("tournament_name"):
            tournament_id = request.POST.get("tournament_id")
            request.session["tournament"]=tournament_id
            url = "polls/"+tournament_id
            return redirect(url, tournament_id)
        else:
            tournament_name = request.POST.get("tournament_name")
            t = Tournament(tournament_name=tournament_name,user_id=user)
            t.save()
            t = t.id
            request.session["tournament"]=t
            url = "polls/"+str(t)
            return redirect(url)
    return render(request, 'tournament.html', {'tournaments':tournaments})

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            url="/polls/choose"
            return redirect(url)
        else:
            return render(request, "login.html", {"message": "Invalid credentials."})
    else:
        return render(request, "login.html", {"message": None})

def logout_view(request):
    logout(request)
    return render(request, "login.html", {"message": "Logged out."})

def tournament(request):
    user=request.session.get("user")
    user=User.objects.get(pk=user)
    tournaments = Tournament.objects.all().filter(user_id=user)
    if request.method == "POST":
        if not request.POST.get("tournament_name"):
            tournament_id = request.POST.get("tournament_id")
            request.session["tournament"]=tournament_id
            url = "polls"+"/"
            return redirect(url)
        else:
            tournament_name = request.POST.get("tournament_name")
            t = Tournament(tournament_name=tournament_name,user_id=user)
            t.save()
            t = t.id
            request.session["tournament"]=t
            url = "polls"+"/"
            return redirect(url)
    return render(request, 'tournament.html', {"tournaments":tournaments,"user":user})

# def existing(request):
#     user=request.session.get("user")
#     tournaments = Tournament.objects.all().filter(user_id=user)
#     if request.method == "POST":
#         tournament_id = request.POST.get("tournament_id")
#         request.session["tournament"]=tournament_id
#         url = "polls"+"/"
#         return redirect(url)
#     return redirect(request, 'existing.html', {'tournaments':tournaments})


def teams(request, level_id, tournament_id):
    t = request.session.get("tournament")
    tournament = Tournament.objects.get(pk=t)
    teams = Team.objects.all().filter(tournament_id=tournament)
    level = Level.objects.get(pk=level_id)
    level.tournament_id = tournament
    level.save()
    user = request.session.get("user")
    user = User.objects.get(pk=user)
    if request.method == "POST":
        if request.POST.get("teamid")==None:
            error="Please choose the team"
            url="/polls/"+str(level_id)+'/teams'
            return redirect(url, {"error":error })
        else:
            team = request.POST.get("teamid")
            t = request.session.get("tournament")
            url="/polls/" + str(t) +'/'+str(level_id)+'/'
            request.session["teamplay"] = team
            return redirect(url)
        
    return render(request, 'teams.html', {'teams':teams,'level':level, 'user':user,'tournament':tournament})

def categories(request, level_id, tournament_id):
    # return HttpResponse("You're looking at level %s." % level_id)
    t = request.session.get("tournament")
    tournament = Tournament.objects.get(pk=t)
    level = Level.objects.get(pk=level_id)
    team = Team.objects.all().filter(tournament_id=tournament)
    teamchosen = request.session.get("teamplay")
    teamchoose = Team.objects.get(pk=teamchosen)
    question = Question.objects.all().filter(tournament_id=tournament)
    # intmarks_alloted = int(Question.marks_alloted)
    # marks_new = intmarks_alloted*0.5
    return render(request, 'categories.html', {'level': level,'team':team, 'teamchoose':teamchoose, 'teamchosen':teamchosen,'tournament':tournament})

def questions(request, category_id, level_id):
    # return HttpResponse("You're looking at level %s." % level_id)
    t = request.session.get("tournament")
    tournament = Tournament.objects.get(pk=t)
    teamchosen = request.session.get("teamplay")
    teamchoose = Team.objects.get(pk=teamchosen)
    level = Category.level
    category = Category.objects.get(pk=category_id)
    return render(request, 'questions.html', {'category': category, 'level':level},)

def specquestion(request, category_id, level_id, question_id,tournament_id):
    # return HttpResponse("You're looking at level %s." % level_id)
    t = request.session.get("tournament")
    tournament = Tournament.objects.get(pk=t)
    question = Question.objects.get(pk=question_id)
    print(question.status)
    category = Category.objects.get(pk=category_id)
    level = Level.objects.get(pk=level_id)
    team = Team.objects.all()
    teamchosen = request.session.get("teamplay")
    teamchoose = Team.objects.get(pk=teamchosen)
    
    return render(request, 'specquestions.html', {'question': question, 'level': level, 'team':team, 'category':category, 'teamchoose':teamchoose,'t':t, 'time':question.time_alloted})

def questionstatus(request, question_id):
    if request.method == "POST":
        t = request.session.get("tournament")
        tournament = Tournament.objects.get(pk=t)
        question = Question.objects.get(pk=question_id)
        teamchosen = request.session.get("teamplay")
        teamchoose = Team.objects.get(pk=teamchosen)
        if request.POST.get('status')==None:
            question.status="PQ"
            print('for save '+question.status)
            question.save()
            print('after save ' + question.status)
            if question.status=="RA":
                teamchoose.team_points += question.marks_alloted
            elif question.status=="PQ":
                question.pass_count += 1
                if question.pass_count == 1:
                    question.marks_alloted = question.marks_alloted/2
                elif question.pass_count >= 2:
                    question.marks_alloted = question.marks_alloted
                teamchoose.team_points += 0
            elif question.status=="WA":
                teamchoose.team_points -= level.negative_marking
            elif question.status=="NA":
                teamchoose.team_points += 0
            question.save()
            teamchoose.save()
            url="/polls/"+str(tournament.id)+"/"+str(question.level.id)+'/teams'
            return redirect(url)
        else:
            question.status=request.POST.get('status')
            print('for save '+question.status)
            question.save()
            print('after save ' + question.status)
            if question.status=="RA":
                teamchoose.team_points += question.marks_alloted
            elif question.status=="PQ":
                question.pass_count += 1
                if question.pass_count == 1:
                    question.marks_alloted = question.marks_alloted/2
                elif question.pass_count >= 2:
                    question.marks_alloted = question.marks_alloted
                teamchoose.team_points += 0
            elif question.status=="WA":
                teamchoose.team_points -= level.negative_marking
            elif question.status=="NA":
                teamchoose.team_points += 0
            question.save()
            teamchoose.save()
            url="/polls/"+str(tournament.id)+"/"+str(question.level.id)+'/teams'
            return redirect(url)

def post_edit(request, pk, ):
    status = get_object_or_404(Question, pk=pk)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=status)
        if form.is_valid():
            status = form.save(commit=False)
            status.save()
            return redirect('/', pk=status.pk)
    else:
        form = QuestionForm(instance=status)

polls/templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Freinds and family screen sharing gaming platform!</title>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
      <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
      <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
      <script>
    function levelFunction() {
  var x = document.getElementById("levels");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
    </script>
  </head>

  <body>

    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

polls/templates/baseform.html
{% extends 'base.html' %}
{% block content %}
<div class="bannercat">
<h1>Question no. {{ question.question_number }}.<br>
    {{question.question_text}}</h1>
    </div>
<div style="text-align:center;">
<br>
    <img src="{{question.image_url}}" alt="" style="width:500px;height:auto;">
<br>
    <br>
{% base content %}
    {% endblock %}
    <a class="btn btn-default" href="{% url 'post_edit' pk=question.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <button type="button" class="btn btn-success" onclick="myFunction();buttonFunction()">Show Answer/Option</button>
<script>


function myFunction() {
  var x = document.getElementById("answers");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}

function buttonFunction() {
  var y = document.getElementById("hi");
  if (y.style.display === "none") {
    y.style.display = "block";
  } else {
    y.style.display = "none";
  }
}

function nextFunction() {
  var y = document.getElementById("next");
  if (y.style.display === "none") {
    y.style.display = "block";
  } else {
    y.style.display = "none";
  }
}
</script>
    <div id="answers" style="display: none;"><br>
    <ul>
        {% for answer in question.answer_set.all %}
        {% if answer.option2 == "" %}
        <b><li>{{answer.option1_answer}}</li></b>
        {% else %}
        <b><li>{{answer.option2}}</li></b>
        <b><li>{{answer.option3}}</li></b>
        <b><li>{{answer.option4}}</li></b>
        {% endif %}
        {% endfor %}
    </ul>

        </div>

    <div id="hi" style="display:none;">
    <button type="button" class="btn btn-danger" onclick="nextFunction()">Wrong</button>
        <button type="button" class="btn btn-success" onclick="nextFunction()">Right</button>
    </div>
    <div id="next" style="display:none"><br>
    <a href="/polls/{{question.level.id}}/{{question.category.id}}"><button type="button" class="btn btn-success">Next Question</button></a>
        <a href="/polls/{{question.level.id}}/"><button type="button" class="btn btn-success">Next Category</button></a>
<!--        <a href='/polls/{{question.level.id}}/{{question.category.id}}'><button type="button" class="btn btn-success">Next Category</button></a>-->
        </div><!-- Optional JavaScript -->

{% endblock %}


</div>

polls/templates/categories.html
<!--{{level}}-->
<html>
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'polls/category.css' %}">
</head>

<body>


    <!-- <div class="bannercat">
<h1>{{ level.level_name }}- Choose the Categories/Question</h1>
</div>

<div class="container" style="padding-top:18px;">
        <div class="row">

        {% for category in level.category_set.all %}

    <div class="card">
  <img src="{{category.image_url}}" class="card-img-top" alt="..." >
  <div class="card-body">
    <h5 class="card-title">{{category.category_name}}</h5>
      <ul class="w3-ul">
      {% for question in category.question_set.all %}

      <p class="card-text">
        <li>
              {% if question.status == "RA" %}
              <strike><span style="color:#27ae60">Question Marks-{{question.marks_alloted}}</span></strike>
              {% elif question.status == "WA" %}
              <strike><span style="color:#e74c3c">Question Marks-{{question.marks_alloted}}</span></strike>
              {% elif question.status == "PQ" %}
              <mark><a href="/polls/{{question.level.id}}/{{category.id}}/{{question.id}}" style="color:#363062">Question Marks-{{question.marks_alloted}}/2</a></mark>
              {% else %}
              <a href="/polls/{{question.level.id}}/{{category.id}}/{{question.id}}" style="color:#000">Question Marks-{{question.marks_alloted}}</a>
              {% endif %}
          </li>

      </p>

      {% endfor %}
      </ul>
<!--    <a href="/polls/{{level.id}}/{{category.id}}" class="btn btn-primary">Category</a>-->
    <!-- </div>
</div>
        {% endfor %}
    </div>

            </div>
        </div>
    </div> -->




    <!-- <div class="board">
    <div class="row categories">
      {% for category in level.category_set.all %}
      <div class="tile">{{category.category_name}}</div>
      {% endfor %}

    </div>
  </div> -->

    <div class="board">

        {% for category in level.category_set.all %}
        <div class="row categories">
            <div class="tile">{{category.category_name}}</div>
            {% for question in category.question_set.all %}
            <div class="tile">
                <div class="question-value">
                    {% if question.status == "RA" %}
                    <span class="ra">{{question.marks_alloted}}</span> {% elif question.status == "WA" %}
                    <span class="wa">{{question.marks_alloted}}</span> {% elif question.status == "PQ" %}
                    <a class="pq" href="/polls/{{tournament.id}}/{{question.level.id}}/{{category.id}}/{{question.id}}">{{question.marks_alloted}}</a> {% else %}
                    <a href="/polls/{{tournament.id}}/{{question.level.id}}/{{category.id}}/{{question.id}}">{{question.marks_alloted}}</a> {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>

    <div class="team">
        <!-- <button type="button" class="btn btn-info" action="polls/{{level.id}}/" method="post">Reset Question Status</button> -->
        {% for team in team %} {% if team.id == teamchoose.id %}
        <div style="width: 100%">
            <div class="tile-e">{{team.team_name}}</div>
            <div class="tile-e">{{team.team_points}}</div>
        </div>
        {% else %}
        <div style="width: 100%">
            <div class="tileui">{{team.team_name}}</div>
            <div class="tileui">{{team.team_points}}</div>
        </div>
        {% endif %} {% endfor %}
    </div>







    </div>

</body>

</html>

polls/templates/choose.html
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <style>
        .card {
            display: flex;
            flex-wrap: wrap;
            margin: 4px;
        }
        
        body {
            padding: 10px;
            text-align: center;
            justify-content: center;
            background: linear-gradient(to bottom, #0250c5 0%, #d43f8d 100%);
            font-family: impact;
        }
        
        h1 {
            text-align: center;
            color: white;
            font-size: 3.5vw;
        }
        
        .form-group {
            text-align: center;
            padding-top: 18px;
        }
        
        .btn {
            padding: 0px !important;
        }
        .card-title {
            text-decoration: none;
            color:black;
        }
        .card-title:hover {
            text-decoration: none;
            color:#6b6b6b;
        }

        .card {
            text-decoration: none;
            color:black;
        }
        .card:hover {
            text-decoration: none;
            color:#6b6b6b;
        }
    </style>

</head>

<body>
    <h1> {{user.first_name}}, What do you want to do?</h1>
    <!-- <a href="/polls/{{level.id}}/">{{team.team_name}}</a> -->
    <div class="row justify-content-center">
        <a href="/master">
            <div class="card" style="width: 250px;">
                    <img src="../static/polls/images/teacher2.jpg" class="card-img-top" alt="..." width="250px" height="250px;">
                    <div class="card-body">
                        <h5 class="card-title">Be the Master</h5>
                        <p class="card-text">
                        </p>
                    </div>
            </div>
        </a>
        <a href="/polls/choosetournament">
            <div class="card" style="width: 250px;">
                    <img src="../static/polls/images/player.jpg" class="card-img-top" alt="..." width="250px" height="250px;">
                    <div class="card-body">
                        <h5 class="card-title">Play Game</h5>
                        <p class="card-text">
                        </p>
                    </div>
            </div>
        </a>
    </div>



</body>

</html>

polls/templates/existing.html
<form action="{% url 'existing' %}" method="post">
    {% csrf_token %}

    <input type="submit">
    <a href="/polls/tournament/existing">Want to continue an existing Tournament?</a>
</form>

polls/templates/firstview.html
{% extends 'base.html' %} {% block content %}
<div class="banner">
    <h1>Play And Win <br> Hello, {{ user }}. This is {{tournament.tournament_name}}
    </h1>
</div>
<div class="gamecard">

    <div class="container">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <center>
                    <h5 class="card-title">Quiz</h5>
                </center>
                <center>
                    <h6 class="card-subtitle mb-2 text-muted">Quiz Game</h6>
                </center>
                <center>
                    <p class="card-text">A Quiz game based on general topics</p>
                </center><br>
                <center><button type="button" class="btn btn-primary" onclick="levelFunction()">Start Game</button>
                    <a type="button" class="btn btn-primary" href="/master/">Logout</a>
                </center>
            </div>
        </div>
    </div>
</div>

<div id="levels" class="levels justify-content-center" style="display:none;">

    <ul class="levelsul">
        {% for level in tournament.level_set.all %}
        <li class="levelsli">
            <a href="/polls/{{tournament.id}}/{{level.id}}/teams" style="text-decoration:none;"><img src="{{level.image_url}}" class="levelimg"><span style="margin-left: 12px;">{{level.level_name}}</span></a>
            </a>
        </li>
        {% endfor %}
    </ul>
    <br>
</div>


{% endblock %}

polls/templates/login.html
{% extends 'formbase2.html' %} {% block content %} {% if message %}
<p class="login-text">
    {{ message }}
</p>
{% else %}
<p class="login-text">Login</p>
{% endif %}

<form action="/polls/login" method="post">
    {% csrf_token %}
    <div class="form-field">
        <label for="username">Username</label>
        <input type="text" name="username" />
    </div>

    <div class="form-field">
        <label for="password">Password</label>
        <input type="password" name="password" />
    </div>

    <div class="form-field">
        <button type="submit" class="login-btn">Login</button>
    </div>
    <!-- <br> -->
    <br>
    <a href="/master/register">
        <p class="login-text" style="padding-top:5px;">Create New User?</p>
    </a>
    <a href="/master/forgotpassword">
        <p class="login-text" style="padding-top:5px;">Forgot Password?</p>
    </a>
</form> 
{% endblock %}

polls/templates/questions.html
{% extends 'base.html' %}
{% block content %}
<html>
<div class="bannercat">
<h1>{{ category.category_name }}- Choose the Question</h1>
</div>
<div style="padding:18px;">
<ul>
    <div class="container">
        <table class="table">
    <thead>
      <tr>
        <th>Question No</th>
        <th>Marks</th>
        <th>Status</th>
      </tr>
    </thead>


        {% for question in category.question_set.all %}
        <tbody>
      <tr>
        <td><a href="/polls/{{question.level.id}}/{{category.id}}/{{question.id}}">Question no. {{ question.question_number }}</a></td>
         <td> <a href="/polls/{{question.level.id}}/{{category.id}}/{{question.id}}">{{question.marks_alloted}} marks</a></td>

          {% if question.status == "RA" %}
          <td style="color:green">Right Answer</td>
          {% elif question.status == "WA" %}
          <td style="color:red">Wrong</td>
          {% else %}
        <td style="color:yellow">Not yet Opened</td>
          {% endif %}
      </tr>

    </tbody>
            {% endfor %}
              </table>
        <a href='/polls/{{category.level.id}}'><button type="button" class="btn btn-success">Next Category</button></a>
    </div>





</div>
</ul>
</html>
{% endblock %}